#!/usr/bin/osascript
tell application "Xcode"
	activate
end tell
delay 0.3
tell application "System Events"
	tell process "Xcode"
		click menu item "Attach to Process by PID or Name…" of menu 1 of menu bar item "Debug" of menu bar 1
	end tell
	delay 0.5
	tell application process "Xcode"
		set value of text field 1 of sheet 1 of window 1 to "Limitless"
	end tell
	delay 0.5
	tell application process "Xcode"
		click button "Attach" of sheet 1 of window 1
	end tell
end tell
